In [0]:
import numpy as np
import torch

In [3]:
tensor = torch.rand(4, 3)
tensor

tensor([[0.6457, 0.6272, 0.6801],
        [0.4449, 0.2177, 0.5949],
        [0.6606, 0.7129, 0.5302],
        [0.9772, 0.8221, 0.6181]])

In [4]:
 type(tensor)

torch.Tensor

In [5]:
numpy_from_tensor = tensor.numpy()
numpy_from_tensor

array([[0.6456787 , 0.62724376, 0.6800793 ],
       [0.44486117, 0.2177198 , 0.5949144 ],
       [0.6605896 , 0.7128732 , 0.5301734 ],
       [0.97715443, 0.82209873, 0.6181252 ]], dtype=float32)

In [6]:
type(numpy_from_tensor)

numpy.ndarray

In [7]:
torch.is_tensor(tensor)

True

In [8]:
torch.is_tensor(numpy_from_tensor)

False

Both Numpy and Torch tensor share the same memory

In [9]:
numpy_from_tensor[0, 0] = 100.0
numpy_from_tensor

array([[100.        ,   0.62724376,   0.6800793 ],
       [  0.44486117,   0.2177198 ,   0.5949144 ],
       [  0.6605896 ,   0.7128732 ,   0.5301734 ],
       [  0.97715443,   0.82209873,   0.6181252 ]], dtype=float32)

In [10]:
tensor

tensor([[100.0000,   0.6272,   0.6801],
        [  0.4449,   0.2177,   0.5949],
        [  0.6606,   0.7129,   0.5302],
        [  0.9772,   0.8221,   0.6181]])

In [0]:
numpy_arr = np.array([[1.0, 2.0, 3.0],
                     [10.0, 20.0, 30.0],
                     [100.0, 200.0, 300.0]])

In [13]:
tensor_from_numpy = torch.from_numpy(numpy_arr)
tensor_from_numpy

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]], dtype=torch.float64)

In [14]:
type(tensor_from_numpy)

torch.Tensor

In [15]:
tensor_from_numpy[0] = 1
tensor_from_numpy

tensor([[  1.,   1.,   1.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]], dtype=torch.float64)

In [16]:
numpy_arr

array([[  1.,   1.,   1.],
       [ 10.,  20.,  30.],
       [100., 200., 300.]])

Using torch.as_tensor to create a tensor from numpy. 

torch.as_tensor does not create a copy

torch.as_tensor is useful if the data is already a tensor with the same dtype and device then no copy is performed and a new tensor is returned with the same computational graph

In [18]:
np_array_one = np.array([4, 8])
np_array_one

array([4, 8])

In [19]:
tensor_from_array_one = torch.as_tensor(np_array_one)
tensor_from_array_one

tensor([4, 8])

In [20]:
np_array_one[1] = 5
np_array_one

array([4, 5])

In [21]:
tensor_from_array_one

tensor([4, 5])

Create a copy when making a tensor from numpy array

In [22]:
np_array_two = np.array([2, 2])
np_array_two

array([2, 2])

In [23]:
tensor_from_array_two = torch.tensor(np_array_two)
tensor_from_array_two

tensor([2, 2])

Change in the numpy array won't reflect in the tensor

In [25]:
np_array_two[1] = 4
np_array_two

array([2, 4])

Here the change won't be reflected

In [26]:
tensor_from_array_two

tensor([2, 2])

In [27]:
torch.cuda.device_count()

0