In [0]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline




In [4]:
%%bash
#check the environemnt 
echo "Check H/W"
lscpu | grep 'CPU(s):            '
lscpu | grep GHz
echo "memory" && free -m | cut -c-49 |  head -n 2 
echo "storage" && df -h |  cut -c-60 | head -n 2
df -h |  grep '/dev/sda1'
echo " " && nvidia-smi -L | cut -c-17
echo "confure Max Application Clock for T4 1590Mhz"
nvidia-smi -ac 5001,1590 && nvidia-smi -pm 1
echo " " &&echo "Check S/W"
cat /etc/*-release | grep PRETTY_NAME
python --version 
nvcc --version | grep  tools


Check H/W
CPU(s):              2
Model name:          Intel(R) Xeon(R) CPU @ 2.30GHz
memory
              total        used        free      
Mem:          13022         420       10561      
storage
Filesystem      Size  Used Avail Use% Mounted on
overlay         359G   30G  311G   9% /
/dev/sda1       365G   39G  327G  11% /opt/bin
 
GPU 0: Tesla T4 (
confure Max Application Clock for T4 1590Mhz
Applications clocks set to "(MEM 5001, SM 1590)" for GPU 00000000:00:04.0


All done.
Enabled persistence mode for GPU 00000000:00:04.0.
All done.
 
Check S/W
PRETTY_NAME="Ubuntu 18.04.2 LTS"
Python 3.6.8
Cuda compilation tools, release 10.0, V10.0.130


In [5]:
!nvidia-smi -q -d SUPPORTED_CLOCKS


==============NVSMI LOG==============

Timestamp                           : Sun Jul  7 21:55:39 2019
Driver Version                      : 410.79
CUDA Version                        : 10.0

Attached GPUs                       : 1
GPU 00000000:00:04.0
    Supported Clocks
        Memory                      : 5001 MHz
            Graphics                : 1590 MHz
            Graphics                : 1575 MHz
            Graphics                : 1560 MHz
            Graphics                : 1545 MHz
            Graphics                : 1530 MHz
            Graphics                : 1515 MHz
            Graphics                : 1500 MHz
            Graphics                : 1485 MHz
            Graphics                : 1470 MHz
            Graphics                : 1455 MHz
            Graphics                : 1440 MHz
            Graphics                : 1425 MHz
            Graphics                : 1410 MHz
            Graphics                : 1395 MHz
            Graphics 

In [6]:
!/opt/bin/nvidia-smi
!nvcc --version

Sun Jul  7 21:55:40 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:04.0 Off |                    0 |
| N/A   46C    P8    16W /  70W |      0MiB / 15079MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU  

In [7]:
!pip3 install https://download.pytorch.org/whl/cu100/torch-1.1.0-cp36-cp36m-linux_x86_64.whl
!pip3 install https://download.pytorch.org/whl/cu100/torchvision-0.3.0-cp36-cp36m-linux_x86_64.whl

In [8]:
import torch

print(torch.__version__)

1.1.0


Default data type in torch is set to torch.float32
CPU and GPU tensor data types are different. Here is the link to all data types:
https://pytorch.org/docs/stable/tensors.html

In [0]:
torch.set_default_dtype(torch.float32)

In [10]:
torch.get_default_dtype()

torch.float32

torch.Tensor uses default data type set using "torch.set_default_dtype" to create a tensor

In [0]:
tensor_arr = torch.Tensor([[1,2,3], [4,5,6]])

In [12]:
tensor_arr

tensor([[1., 2., 3.],
        [4., 5., 6.]])

Check if an array is a tensor

In [13]:
torch.is_tensor(tensor_arr)

True

Check number of elements in an array

In [14]:
torch.numel(tensor_arr)

6

Creating a tensor by only specifying it's shape

In [0]:
tensor_uninitialized = torch.Tensor(2,2)

In [16]:
tensor_uninitialized

tensor([[1.2794e-36, 0.0000e+00],
        [4.4842e-44, 0.0000e+00]])

torch.rand initializes a 2x2 matrix of random values




In [0]:
tensor_initialized = torch.rand(2, 2)

Creating a tensor with particular data type

In [0]:
tensor_int = torch.tensor([5, 3]).type(torch.IntTensor)

In [19]:
tensor_short = torch.ShortTensor([1.0,2.0,3.0])
tensor_short

tensor([1, 2, 3], dtype=torch.int16)

2x6 tensor filled with 10's

In [20]:
tensor_fill = torch.full((2, 6), fill_value=10)
tensor_fill

tensor([[10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10.]])

In [21]:
tensor_of_ones = torch.ones([2, 4], dtype=torch.int32)
tensor_of_ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

"_like" creates a tensor of same type

In [22]:
tensor_of_zeros = torch.zeros_like(tensor_of_ones)
tensor_of_zeros

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [23]:
tensor_eye = torch.eye(5)
tensor_eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

torch.nonzero ??

In [0]:
non_zero = torch.nonzero(tensor_eye)

Sparse tensors

In [0]:
i = torch.tensor([[0, 1, 1],
                 [2, 2, 0]])

In [0]:
v = torch.tensor([3, 4, 5])

In [0]:
 sparse_tensor = torch.sparse_coo_tensor(i, v, [2,5])

In [28]:
sparse_tensor.data

tensor(indices=tensor([[0, 1, 1],
                       [2, 2, 0]]),
       values=tensor([3, 4, 5]),
       size=(2, 5), nnz=3, layout=torch.sparse_coo)

Replace all elements of a tensor with another value.
Here _fill replaces the original tensor

In [29]:
initial_tensor = torch.rand(2, 3)
initial_tensor

tensor([[0.2655, 0.0397, 0.5011],
        [0.6105, 0.1642, 0.8019]])

In [30]:
initial_tensor.fill_(10)

tensor([[10., 10., 10.],
        [10., 10., 10.]])

Add a number to each of the elements in tensor

In [31]:
new_tensor = initial_tensor.add(5)
new_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

_add replaces the original tensor

In [32]:
initial_tensor.add_(8)
initial_tensor

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [33]:
new_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [34]:
new_tensor.sqrt_()

tensor([[3.8730, 3.8730, 3.8730],
        [3.8730, 3.8730, 3.8730]])

In [35]:
x = torch.linspace(start=0.1, end=10.0, steps=15)
x

tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])

Split the tensor

In [36]:
tensor_chunk = torch.chunk(x, 3, 0)
tensor_chunk

(tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286]),
 tensor([3.6357, 4.3429, 5.0500, 5.7571, 6.4643]),
 tensor([ 7.1714,  7.8786,  8.5857,  9.2929, 10.0000]))

Split and combine tensors

In [37]:
tensor1 = tensor_chunk[0]
tensor2 = tensor_chunk[1]
tensor3 = torch.tensor([3.0, 4.0, 5.0])

torch.cat((tensor1, tensor2, tensor3), 0)

tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286, 3.6357, 4.3429, 5.0500, 5.7571,
        6.4643, 3.0000, 4.0000, 5.0000])

In [38]:
random_tensor = torch.Tensor([[10, 8, 30], [40, 5, 6], [12, 2, 2]])
random_tensor

tensor([[10.,  8., 30.],
        [40.,  5.,  6.],
        [12.,  2.,  2.]])

In [39]:
random_tensor[0, 1]

tensor(8.)

Accessing all rows from row1 onwards and accessing all columns from column1 onwards in random_tensor

In [40]:
random_tensor[1:, 1:]

tensor([[5., 6.],
        [2., 2.]])

In [41]:
random_tensor.size()

torch.Size([3, 3])

View 3x3 tensor as a row of 9 elements

In [0]:
resized_tensor = random_tensor.view(9)

In [43]:
resized_tensor.size()

torch.Size([9])

In [44]:
random_tensor[2, 2] = 100.0
resized_tensor

tensor([ 10.,   8.,  30.,  40.,   5.,   6.,  12.,   2., 100.])

In [45]:
random_tensor
random_tensor.shape

torch.Size([3, 3])

Create a tensor with additionaldimension

In [46]:
tensor_unsequeeze = torch.unsqueeze(random_tensor, 2)
tensor_unsequeeze

tensor([[[ 10.],
         [  8.],
         [ 30.]],

        [[ 40.],
         [  5.],
         [  6.]],

        [[ 12.],
         [  2.],
         [100.]]])

In [47]:
tensor_unsequeeze.shape

torch.Size([3, 3, 1])

In [48]:
initial_tensor

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [49]:
tensor_transpose = torch.transpose(initial_tensor, 0, 1 )
tensor_transpose

tensor([[18., 18.],
        [18., 18.],
        [18., 18.]])

In [50]:
random_tensor

tensor([[ 10.,   8.,  30.],
        [ 40.,   5.,   6.],
        [ 12.,   2., 100.]])

In [51]:
sorted_tensor, sorted_indices = torch.sort(random_tensor)
sorted_tensor

tensor([[  8.,  10.,  30.],
        [  5.,   6.,  40.],
        [  2.,  12., 100.]])

In [52]:
sorted_indices

tensor([[1, 0, 2],
        [1, 2, 0],
        [1, 0, 2]])

In [53]:
tensor_float = torch.FloatTensor([-1.1, -2.2, 3.3])
tensor_float

tensor([-1.1000, -2.2000,  3.3000])

In [54]:
tensor_abs = torch.abs(tensor_float)
tensor_abs

tensor([1.1000, 2.2000, 3.3000])

In [55]:
tensor_abs.dtype

torch.float32

In [0]:
rand1 = torch.abs(torch.randn(2, 3))
rand2 = torch.abs(torch.randn(2, 3))

In [57]:
rand1

tensor([[2.5151, 0.5895, 0.6141],
        [1.3217, 2.5297, 0.7184]])

In [58]:
rand2

tensor([[0.7912, 0.7128, 0.5596],
        [1.0271, 0.1640, 1.8476]])

In [61]:
add1 = rand1 + rand2
add1

tensor([[3.3063, 1.3023, 1.1737],
        [2.3488, 2.6937, 2.5661]])

Elementwise addition

In [0]:
add2 = torch.add(rand1, rand2)

Elementwise division

In [0]:
tensor = torch.Tensor([[-1, -2, -3], 
                      [1, 2, 3]])

In [0]:
torch_div = torch.div(tensor, tensor + 0.3)

Elementwise multiplication

In [69]:
tensor_mul = torch.mul(tensor, tensor)
tensor_mul

tensor([[1., 4., 9.],
        [1., 4., 9.]])

Clamp numbers inside a matrix

In [71]:
tensor_clamp = torch.clamp(tensor, min=-0.2, max=2)
tensor_clamp

tensor([[-0.2000, -0.2000, -0.2000],
        [ 1.0000,  2.0000,  2.0000]])

Calculate dot product

In [0]:
t1 = torch.Tensor([1, 2])
t2 = torch.Tensor([10, 20])

In [74]:
dot_product = torch.dot(t1, t2)
dot_product

tensor(50.)

Vector and Matrix multiplication

In [0]:
matrix = torch.Tensor([[1, 2, 3],
                      [4, 5, 6]])

vector = torch.Tensor([0, 1, 2])

In [78]:
matrix_vector = torch.mv(matrix, vector)
matrix_vector

tensor([ 8., 17.])

Matrix and Matrix multiplication

In [82]:
another_matrix = torch.Tensor([[10, 30],
                              [20, 0],
                              [0, 50]])
matrix_mul = torch.mm(matrix, another_matrix)
matrix_mul

tensor([[ 50., 180.],
        [140., 420.]])

Find the largest element among a dimension

In [83]:
torch.argmax(matrix_mul, dim=1)

tensor([1, 1])

Find the smallest element along a dimension

In [84]:
torch.argmin(matrix_mul, dim=1)

tensor([0, 0])